# -*- coding: utf-8 -*-
"""Pass/Fail Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djrKkI2hpCyeFRPzewRHOtzGntaIjsKM
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

import matplotlib.pyplot as plt

df = pd.read_csv("phase2_risk_clusters.csv")
df.shape
df.head()
df.info()

"""Define pass/fail label"""

df['pass_fail'] = (df['failed_courses'] >= 60).astype(int)
df['pass_fail'].value_counts(normalize=True)

df.columns.tolist()

features = [
 'total_time_spent',
 'active_days',
 'access_frequency',
 'avg_quiz_score',
 'quiz_score_std',
 'avg_assignment_score',
 'late_submission_ratio',
 'avg_final_grade',
 'risk_level',
 'risk_cluster_encoded'

]

"""Missing sets"""

missing = set(features) - set(df.columns)
missing

risk_mapping = {
    'Low Risk': 0,
    'Medium Risk': 1,
    'High Risk': 2
}

df['risk_cluster_encoded'] = df['risk_cluster'].map(risk_mapping)
df[['risk_cluster', 'risk_cluster_encoded']].head()

X = df[features]
y = df['pass_fail']

X.shape, y.shape

"""Train/Test split"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

"""Log Reg"""

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

