# -*- coding: utf-8 -*-
"""burnoutdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yp2vCSWQQSSBPtEIdokcHlHhRVTO96nA
"""

# Cell 1: Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
    ConfusionMatrixDisplay
)
from sklearn.feature_selection import SelectKBest, f_classif

# Cell 2: Load your dataset
df = pd.read_csv('academIQ_burnout_dataset_final.csv')

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nBurnout risk distribution:")
print(df['burnout_risk'].value_counts())
df.head()

# Cell 3: Define features — leaking columns already removed
feature_cols = [
    'all_clicks',
    'active_days',
    'access_frequency',
    'material_clicks',
    'avg_quiz_score',
    'quiz_attempts',
    'avg_assignment_score',
    'assignment_submissions',
    'total_time_spent',
    'procrastination_index',
    'late_submission_count',
    'spike_count',
    'crash_count',
    'decline_weeks',
    'avg_instability',
    'max_instability'
]

X = df[feature_cols].copy()
y = df['burnout_risk'].copy()

X = X.fillna(X.median())

print("Features shape:", X.shape)
print("Target distribution:")
print(y.value_counts())

# Cell 4: Split on real data only — no synthetic data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"Training set size: {X_train.shape[0]} students")
print(f"Testing set size:  {X_test.shape[0]} students")
print(f"\nLabel distribution in training set:")
print(y_train.value_counts())
print(f"\nLabel distribution in test set:")
print(y_test.value_counts())

# Cell 5: Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print("Features scaled ✓")
print("No synthetic data used — 100% real students ✓")

# Cell 6: Feature selection — keep only statistically significant features
selector = SelectKBest(score_func=f_classif, k='all')
selector.fit(X_train_scaled, y_train)

feature_scores = pd.DataFrame({
    'feature': feature_cols,
    'score': selector.scores_,
    'p_value': selector.pvalues_
}).sort_values('score', ascending=False)

print("Feature scores (higher = more important):")
print(feature_scores.to_string(index=False))

# Keep only statistically significant features (p_value < 0.05)
significant_features = feature_scores[
    feature_scores['p_value'] < 0.05
]['feature'].tolist()

print(f"\nOriginal features: {len(feature_cols)}")
print(f"Selected features: {len(significant_features)}")
print(f"\nDropped: {[f for f in feature_cols if f not in significant_features]}")

X_train_selected = X_train_scaled[:, [feature_cols.index(f) for f in significant_features]]
X_test_selected  = X_test_scaled[:,  [feature_cols.index(f) for f in significant_features]]

print("\nNew training set shape:", X_train_selected.shape)
print("New test set shape:    ", X_test_selected.shape)

# Cell 7: Train Random Forest model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train_selected, y_train)
print("Random Forest model trained ✓")

# Cell 8: Make predictions with threshold comparison then set best threshold
y_prob = model.predict_proba(X_test_selected)[:, 1]

# Compare thresholds
for threshold in [0.50, 0.55, 0.60, 0.65, 0.70]:
    y_pred_thresh = (y_prob >= threshold).astype(int)
    print(f"\n--- Threshold: {threshold} ---")
    print(classification_report(y_test, y_pred_thresh,
                                target_names=['Safe', 'Burnout Risk']))

# Best threshold chosen based on results
BEST_THRESHOLD = 0.50
y_pred = (y_prob >= BEST_THRESHOLD).astype(int)

print(f"\nUsing threshold: {BEST_THRESHOLD}")
print(f"Predicted at-risk students: {y_pred.sum()}")
print(f"Actual at-risk students:    {y_test.sum()}")

# Cell 9: Classification report with best threshold
print("=" * 50)
print("CLASSIFICATION REPORT")
print("=" * 50)
print(classification_report(
    y_test, y_pred,
    target_names=['Safe', 'Burnout Risk']
))

auc = roc_auc_score(y_test, y_prob)
print(f"AUC Score: {auc:.4f}")

if auc >= 0.90:
    print("Excellent model ✓")
elif auc >= 0.80:
    print("Good model ✓")
elif auc >= 0.70:
    print("Acceptable model")
else:
    print("Model needs improvement")

# Cell 10: Confusion matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['Safe', 'Burnout Risk']
)

fig, ax = plt.subplots(figsize=(6, 5))
disp.plot(ax=ax, colorbar=False, cmap='Blues')
ax.set_title('Confusion Matrix — Burnout Risk Detection')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

tn, fp, fn, tp = cm.ravel()
print(f"\nCorrectly identified at-risk students (TP): {tp}")
print(f"Missed at-risk students (FN):               {fn}")
print(f"Falsely flagged safe students (FP):         {fp}")
print(f"Correctly identified safe students (TN):    {tn}")

# Cell 11: ROC curve
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, color='#534AB7', lw=2,
         label=f'Random Forest (AUC = {auc:.4f})')
plt.plot([0, 1], [0, 1], 'k--', lw=1, label='Random guessing')
plt.xlabel('False Positive Rate (falsely flagged safe students)')
plt.ylabel('True Positive Rate (correctly caught at-risk students)')
plt.title('ROC Curve — Burnout Risk Detection')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('roc_curve.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 12: Feature importance from Random Forest
importance_df = pd.DataFrame({
    'feature': significant_features,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=True)

colors = ['#E24B4A' if x > importance_df['importance'].median()
          else '#5DCAA5' for x in importance_df['importance']]

plt.figure(figsize=(8, 7))
plt.barh(importance_df['feature'], importance_df['importance'], color=colors)
plt.xlabel('Importance Score')
plt.title('Feature Importance — Random Forest\nRed = more important  |  Green = less important')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nTop 5 most important features:")
print(importance_df.sort_values('importance', ascending=False)
      .head(5)[['feature', 'importance']].to_string(index=False))

# Cell 13: Apply model to all real students
X_real = df[feature_cols].fillna(df[feature_cols].median())
X_real_scaled = scaler.transform(X_real)
X_real_selected = X_real_scaled[:, [feature_cols.index(f) for f in significant_features]]

df['burnout_probability'] = model.predict_proba(X_real_selected)[:, 1]
df['burnout_predicted']   = (df['burnout_probability'] >= BEST_THRESHOLD).astype(int)

def get_risk_level(prob):
    if prob >= 0.80:
        return 'High Risk'
    elif prob >= 0.55:
        return 'Medium Risk'
    elif prob >= 0.30:
        return 'Low Risk'
    else:
        return 'Safe'

df['risk_level'] = df['burnout_probability'].apply(get_risk_level)

print("Risk level distribution:")
print(df['risk_level'].value_counts())

print("\nSample predictions:")
df[['student_id', 'burnout_probability',
    'burnout_predicted', 'risk_level']].head(10)

# Cell 14: Save final results
df.to_csv('burnout_model_results.csv', index=False)

from google.colab import files
files.download('burnout_model_results.csv')

print("Saved ✓")
print(f"\nFinal dataset shape: {df.shape}")
print(f"\nRisk level summary:")
print(df['risk_level'].value_counts())
print(f"\nModel AUC: {auc:.4f}")

# Cell 15: Save the trained model
import joblib

# Save the model, scaler, and significant features list
joblib.dump(model, 'burnout_model.pkl')
joblib.dump(scaler, 'burnout_scaler.pkl')
joblib.dump(significant_features, 'burnout_features.pkl')

print("Model saved ✓")
print("Scaler saved ✓")
print("Features list saved ✓")

# Download all three files
from google.colab import files
files.download('burnout_model.pkl')
files.download('burnout_scaler.pkl')
files.download('burnout_features.pkl')